substitutions:
  node_platform: ESP8266
  node_board: esp01_1m

packages:
  device_base: !include ../common/base.yaml
  basic_sensors: !include ../common/basic_sensors.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: ${friendly_name} Button
    id: button
    on_press:
      - switch.toggle: device_switch

logger:
  baud_rate: 0

uart:
  rx_pin: RX
  baud_rate: 4800

sensor:
  - platform: cse7766
    update_interval: 5s
    current:
      name: ${friendly_name} Current
      id: current

    voltage:
      name: ${friendly_name} Voltage
      id: voltage

    power:
      name: ${friendly_name} Power
      id: power
      on_value:
        then:
          - sensor.template.publish:
              id: "apparent_power"
              state: !lambda "return id(voltage).state * id(current).state;"
          - sensor.template.publish:
              id: "power_factor"
              state: !lambda "return id(power).state / (id(voltage).state * id(current).state);"

  - platform: template
    name: ${friendly_name} Apparent Power
    id: apparent_power
    unit_of_measurement: W

  - platform: template
    name: ${friendly_name} Power Factor
    id: power_factor

  - platform: total_daily_energy
    name: ${friendly_name} Total Daily Energy
    power_id: power
    id: device_total_daily_energy

switch:
  - platform: gpio
    name: ${friendly_name}
    pin: GPIO12
    id: device_switch

status_led:
  pin: GPIO13

time:
  - platform: sntp
    id: current_time
