esphome:
  board: ${node_board}
  platform: ${node_platform}
  name: ${hostname}
  build_path: ./build/${hostname}
  arduino_version: recommended

logger:
  level: DEBUG

api:
  reboot_timeout: 15min

ota:

wifi:
  ssid: !secret WIFI_SSID
  password: !secret WIFI_PASSWORD
  fast_connect: true
  reboot_timeout: 300s
  domain: !secret WIFI_DOMAIN
  ap:
    ssid: ${friendly_name} Hotspot
    password: !secret WIFI_PASSWORD
